apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http
  namespace: default
spec:
  parentRefs:
  - name: gateway
    kind: 
    port: 
    sectionName: 
    namespace: istio-ingress
    group: 
  hostnames: ["www.kubedom.com"]
  rules:
    - backendRefs:
      - name: httpbin
        weight: 
        port: 8000
        kind: 
        group: 
    - matches:
      - path:
          type: PathPrefix
          value: /ip
          type: PathPrefix
          value: /headers
    - filters:
      - type: RequestHeaderModifier
        requestHeaderModifier:
          add:
            - name: my-added-header
              value: added-value
