apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
        - name: prom-busy-bos-set-permis
          image: busybox
          command: ["/bin/chmod","-R","777","/var/lib/grafana"]
          volumeMounts:
          - name: grafana-storage
            mountPath: /var/lib/grafana
      containers:
        - name: grafana
          image: grafana/grafana:latest
          args: 
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/datasources
      volumes:
        - name: grafana-config
          configMap:
            name: grafana-config
            defaultMode: 420
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: pvc1-store
