apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-csi-data
  namespace: monitoring
  labels:
    app: prometheus-deployment
spec:
  storageClassName: sc-prom
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
