apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1-data
  namespace: monitoring
  labels:
    app: prometheus-deployment
spec:
  storageClassName: prom1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 11Gi
