Version: v1
kind: PersistentVolumeClaim
Name for this kind: pvc1-data 
Namespaces that you want this kind to be deployed: monitoring
app name to be referenced: prometheus-deployment 
User defined Name for the Storage Class: prom1 
The Access Modes Value needs to be mentioned Read/Write/ReadWrite etc: ReadWriteOnce
The storage Details(Mb/Gb): 11Gi
