apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-nfs-data
  namespace: monitoring
  labels:
    type: csi
    app: prometheus-deployment
spec:
  storageClassName: managed-nfs
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: ebs.csi.aws.com
