apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-csi-data
  namespace: monitoring
  labels:
    type: csi
    app: prometheus-deployment
spec:
  storageClassName: slow
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: csihandle
