apiVersion:
kind:
metadata:
  name:
  namespace:
  labels:
    app:
spec:
  replicas:
  selector:
    matchLabels:
      app:
  strategy:
    rollingUpdate:
      maxSurge:
      maxUnavailable:
    type:
  template:
    metadata:
      labels:
        app:
  revisionHistoryLimit:
  minReadySeconds:
  progressDeadlineSeconds:
    metadata:
      labels:
        app:
    spec:
      nodeSelector:
      nodeName:
      restartPolicy:
      initContainers:
        - name:
          image:
          command:
          volumeMounts:
          - name:
      name:
      image:
      imagePullPolicy:
      command:
      args:
      workingDir:
      env:
        name:
        value:
        valueFrom:
          configMapKeyRef:
            key:
            name:
            optional:
          fieldRef:
          resourceFieldRef:
          secretKeyRef:
            key:
            name:
            optional:
      envFrom:
        configMapRef:
          name:
          optional:
        prefix:
        secretRef:
          name:
          optional:
      ports:
        containerPort:
        hostIP:
        hostPort:
        name:
        protocol:
      volumeMounts:
        name:
        mountPropagation
        readOnly:
        subPath:
        subPathExpr:
      volumeDevices:
        devicePath:
        name:
