apiVersion:
kind:
metadata:
  name:
  namespace:
  labels:
    app:
spec:
  replicas:
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
        - name:
          image:
          args:
          ports:
            - containerPorts:
          volumeMounts:
            - name:
      volumes:
        - name:
          configMap:
            name:
