apiVersion:
kind:
metadata:
  name:
  namespace:
  labels:
    app:
spec:
  replicas:
  selector:
    matchLabels:
      app:
  strategy:
    rollingUpdate:
      maxSurge:
      maxUnavailable:
    type:
  revisionHistoryLimit:
  minReadySeconds:
  progressDeadlineSeconds:
  template:
    metadata:
      labels:
        app:
    spec:
      restartPolicy:
      initContainers:
        - name:
          image:
          command:
          volumeMounts:
          - name:
      containers:
      - name:
        image:
        imagePullPolicy:
        command:
        args:
        ports:
          - containerPort:
            hostIP:
            name:
            protocol:
        volumeMounts:
          - name:
            mountPropagation:
            readOnly:
            subPath:
            subPathExpr:
      volumes:
        - name:
          persistentVolumeClaim:
            claimName:
        - name:
          configMap:
            name:
